name: Dispatch build event to cyrus01337/neovim-devcontainer

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    trigger-event:
        name: Dispatch build event
        runs-on: ubuntu-latest
        steps:
            - name: Parse short commit hash
              run: |
                SHORT_COMMIT_HASH=$(git rev-parse --short $GITHUB_SHA)

                echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_ENV

            - name: Dispatch
              run: |
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/cyrus01337/neovim-devcontainer/dispatches \
                    -d '{"event_type":"Handle build request (neovim-configuration@${{ env.SHORT_COMMIT_HASH }}"}'
